# Generated by Django 4.0.1 on 2022-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
