# Generated by Django 4.0.1 on 2022-04-24 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regidb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xyz', models.ImageField(null=True, upload_to='media')),
                ('uname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('upassword', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('profession', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
