# Generated by Django 4.0.1 on 2022-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidb',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
