# Generated by Django 4.0.1 on 2022-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_regidb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, null=True)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('cemail', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
