# Generated by Django 4.0.1 on 2022-04-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidb',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
