# Generated by Django 4.0.1 on 2022-04-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_regidb_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500, null=True)),
                ('mid', models.IntegerField(null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.regidb')),
            ],
        ),
    ]
