# Generated by Django 4.0.1 on 2022-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_messagedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidb',
            name='active',
            field=models.IntegerField(null=True),
        ),
    ]
